import 'package:freezed_annotation/freezed_annotation.dart';

part 'member.freezed.dart';

/// Status values for a member, matching the `status` column in
/// `public.members`. The database remains the source of truth; this enum
/// only provides safe typed access for the UI.
enum MemberStatus { active, inactive, blocked }

extension MemberStatusX on MemberStatus {
  /// Maps a database status string to a [MemberStatus].
  ///
  /// Returns `null` for unknown values so callers can fail safely instead of
  /// silently downgrading.
  static MemberStatus? fromWireName(String? value) {
    for (final status in MemberStatus.values) {
      if (status.name == value) {
        return status;
      }
    }
    return null;
  }

  /// Human-readable status label for the UI.
  String get label {
    return switch (this) {
      MemberStatus.active => 'Active',
      MemberStatus.inactive => 'Inactive',
      MemberStatus.blocked => 'Blocked',
    };
  }

  bool get isActive => this == MemberStatus.active;
  bool get isBlocked => this == MemberStatus.blocked;
}

/// Optional gender values. Unknown or missing values map to `null` so the
/// field stays optional.
enum MemberGender { male, female }

extension MemberGenderX on MemberGender {
  static MemberGender? fromWireName(String? value) {
    for (final gender in MemberGender.values) {
      if (gender.name == value) {
        return gender;
      }
    }
    return null;
  }

  String get label {
    return switch (this) {
      MemberGender.male => 'Male',
      MemberGender.female => 'Female',
    };
  }
}

/// A gym member (not an application user).
///
/// [memberCode] is generated by the database trigger and must never be
/// created or edited client-side. [organizationId] comes from the
/// authenticated tenant context and is never user-selectable.
@freezed
abstract class Member with _$Member {
  const factory Member({
    required String id,
    required String organizationId,
    String? branchId,
    String? memberCode,
    required String fullName,
    required String phone,
    MemberGender? gender,
    DateTime? dateOfBirth,
    String? photoUrl,
    String? notes,
    @Default(MemberStatus.active) MemberStatus status,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) = _Member;

  const Member._();
}
